name: Generate Product Feeds

on:
  schedule:
    # Ejecutar cada día a las 2 AM (hora de México)
    - cron: '0 8 * * *'  # 8 UTC = 2 AM México
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate feeds
      run: python feed_processor.py
    
    - name: Upload feeds as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: product-feeds
        path: output/
        retention-days: 30
    
    - name: Deploy to GitHub Pages (opcional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        cname: feeds.accu-chek.com.mx  # Si tienes dominio personalizado