name: Simple Feed Generator

on:
  schedule:
    # Run daily at 2 AM Mexico time
    - cron: '0 8 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-feeds:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate feeds
      run: python feed_processor.py
    
    - name: Upload feeds as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: product-feeds
        path: output/
        retention-days: 7